server:
  port: 8081
  servlet:
    context-path: /crud

spring:
  application:
    name: crud
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
      dialect: org.postgresql.Driver
#
  jmx:
    enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/crud
    username: microservices
    password: microservices123      
      
      
    
    
    
   

